language: ruby
rvm:
  - 2.2

before_install:
  - gem update --system
  - gem update bundler

addons:
  apt:
    packages:
      - libyajl2

bundler_args: --without benchmark
script: bundle exec rake test
cache: bundler
dist: trusty
